### ISSUE TITLE
**Is your feature request related to a problem? Please describe.**

### ISSUE THREAD

**Issue by ghost** [opensource-apple/objc4#40]
**Is your feature request related to a problem? Please describe.**
In ownCloud app we have a comprehensive set of settings which can be used for branding, MDM, configuration during development. _AppConfig_ spec files are maintained manually.

When a new setting is added or an existing setting is changed in code, class settings metadata should be used to automatically generate an updated version of the AppConfig spec file.

**Describe the solution you'd like**
A script, unit test or tool using the `OCClassSettings` metadata to generate the `AppConfig` spec XML files automatically. 

It should generate different versions with varying degrees of detail/sets of settings based on the `status`.

### RELATED ISSUES

#755 on automatic generation of documentation from metadata.

### TASKS

- [x] Research (if needed)
- [ ] Create branch feature/feature_name
- [x] Development tasks
  - [x] Implement whatever
  - [x] ...
- [x] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [x] Merge branch feature/feature_name into master

__Originally posted by @felix-schwarz in https://github.com/owncloud/ios-app/issues/842__
